# ─────────────────────────────────────────────────────────
# models/interview.py — AI Interview Session Model
# ─────────────────────────────────────────────────────────
# PURPOSE:
#   Stores the data for the AI Interview Bot session.
#   Each application can have ONE AI interview.
# ─────────────────────────────────────────────────────────

from sqlalchemy import Column, Integer, String, Float, DateTime, ForeignKey, JSON, Text
from sqlalchemy.sql import func
from sqlalchemy.orm import relationship
from core.database import Base

class Interview(Base):
    """
    Represents an AI Interview session.
    
    Database Table: `interviews`
    """
    __tablename__ = "interviews"

    id = Column(Integer, primary_key=True, index=True)
    
    # application_id: Links this interview to a specific job application.
    application_id = Column(Integer, ForeignKey("applications.id", ondelete="CASCADE"), unique=True, nullable=False)

    # ── Session State ─────────────────────────────────────
    # chat_history: Stores the full conversation as a JSON list.
    # e.g., [{"role": "ai", "content": "Hello..."}, {"role": "user", "content": "Hi..."}]
    chat_history = Column(JSON, default=list)
    
    # current_question_index: Tracks progress during the interview.
    current_question_index = Column(Integer, default=0)

    # ── AI Evaluation ─────────────────────────────────────
    # interview_score: Final score assigned by the AI Bot (0.0 to 100.0).
    interview_score = Column(Float, nullable=True)
    
    # feedback_summary: Detailed feedback generated by OpenAI.
    feedback_summary = Column(Text, nullable=True)

    # ── Status ────────────────────────────────────────────
    is_completed = Column(String(50), default="scheduled") # scheduled, in_progress, completed, failed
    started_at = Column(DateTime(timezone=True), nullable=True)
    completed_at = Column(DateTime(timezone=True), nullable=True)

    # ── Relationships ─────────────────────────────────────
    application = relationship("Application", back_populates="interview")

    def __repr__(self):
        return f"<Interview id={self.id} application_id={self.application_id} score={self.interview_score}>"
