# ─────────────────────────────────────────────────────────
# models/job.py — Full Job Posting Model
# ─────────────────────────────────────────────────────────
# PURPOSE:
#   This is the central table for all job postings.
#   HR users create these. Seekers search and apply to these.
# ─────────────────────────────────────────────────────────

from sqlalchemy import Column, Integer, String, Boolean, DateTime, Text, ForeignKey, Enum
from sqlalchemy.sql import func
from sqlalchemy.orm import relationship
import enum

from core.database import Base


# ── Job Status Enum ──────────────────────────────────────
class JobStatus(str, enum.Enum):
    DRAFT = "draft"          # HR is still writing it
    PUBLISHED = "published"  # Live and visible to seekers
    CLOSED = "closed"        # No longer accepting applications


class Job(Base):
    """
    Represents a Job Posting in the system.
    
    Database Table: `jobs`
    """
    __tablename__ = "jobs"

    # ── Identifiers ───────────────────────────────────────
    id = Column(Integer, primary_key=True, index=True)
    
    # company_id: Links this job to the company that posted it.
    company_id = Column(Integer, ForeignKey("companies.id", ondelete="CASCADE"), nullable=False)
    
    # creator_id: Links to the specific HR user who created this posting.
    creator_id = Column(Integer, ForeignKey("users.id"), nullable=False)

    # ── Job Details ───────────────────────────────────────
    title = Column(String(255), nullable=False, index=True)
    
    # description: Full job description (often generated by AI).
    description = Column(Text, nullable=False)

    # requirements: Skills, qualifications, and experience needed.
    requirements = Column(Text, nullable=True)
    
    # short_description: A 1-2 sentence summary for cards/lists.
    short_description = Column(String(500), nullable=True)

    # ── Meta Info ─────────────────────────────────────────
    location = Column(String(255), nullable=True)  # e.g., "Remote" or "Bangalore"
    job_type = Column(String(100), nullable=True)  # e.g., "Full-time", "Contract"
    salary_range = Column(String(100), nullable=True) # e.g., "10L - 15L"
    experience_required = Column(String(100), nullable=True) # e.g., "3+ years"

    # ── Status & Settings ─────────────────────────────────
    status = Column(Enum(JobStatus), default=JobStatus.DRAFT, nullable=False)
    is_ai_interview_enabled = Column(Boolean, default=True) # Should system trigger AI interview?

    # ── Timestamps ────────────────────────────────────────
    created_at = Column(DateTime(timezone=True), server_default=func.now())
    updated_at = Column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now())

    # ── Relationships ─────────────────────────────────────
    company = relationship("Company", back_populates="jobs")
    creator = relationship("User") # Link to the HR user
    applications = relationship("Application", back_populates="job", cascade="all, delete-orphan")

    def __repr__(self):
        return f"<Job id={self.id} title='{self.title}' company_id={self.company_id}>"
